name: WispSuperItems
version: ${project.version}
main: dev.yhdiamond.wispsuperitems.WispSuperItems
api-version: 1.16
commands:
  wispsuperitems:
    usage: /wispsuperitems <start/stop>
    description: Starts the Wisp Super Items challenge.